apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value |b64enc }}
{{- end }}
