replicaCount: 1

image:
  repository: ghcr.io/scientist-softserv/bookstack
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: github

serviceAccount:
  create: true
  automount: true
  name: bookstack

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx,
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  }
  hosts:
    - host: bookstack.notch8.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: bookstack-tls
      hosts:
        - bookstack.notch8.cloud

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: $MARIADB_ROOT_PASSWORD
    database: bookstack
    username: mariadb
    password: $MARIADB_PASSWORD
  primary:
    persistence:
      enabled: true
      storageClass: "gp2"
      accessModes:
        - ReadWriteOnce
      size: 10Gi

volumes:
  - name: public-uploads
    persistentVolumeClaim:
      claimName: public-uploads
  - name: storage-uploads
    persistentVolumeClaim:
      claimName: storage-uploads

volumeMounts:
  - name: public-uploads
    mountPath: "/var/www/html/bookstack/public/uploads"
  - name: storage-uploads
    mountPath: "/var/www/html/bookstack/storage/uploads"

mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: $MARIADB_ROOT_PASSWORD
    database: bookstack
    username: mariadb
    password: $MARIADB_PASSWORD
  primary:
    persistence:
      enabled: true
      storageClass: "gp2"
      accessModes:
        - ReadWriteOnce
      size: 10Gi

env:
  APP_ENV: production
  APP_URL: https://bookstack.notch8.cloud
  APP_KEY: $APP_KEY
  MARIADB_HOST: bookstack-production-mariadb
  MARIADB_DATABASE: bookstack
  MARIADB_USER: mariadb
  MARIADB_PASSWORD: $MARIADB_PASSWORD
  MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
  STORAGE_TYPE: local_secure_restricted
  STORAGE_IMAGE_TYPE: local_secure_restricted
  STORAGE_ATTACHMENT_TYPE: local_secure_restricted
  # MAIL_DRIVER: smtp
  # MAIL_HOST: localhost
  # MAIL_PORT: 2525
  # MAIL_USERNAME: your-smtp-username
  # MAIL_PASSWORD: $MAIL_PASSWORD
  # MAIL_ENCRYPTION: tls
  # MAIL_FROM_ADDRESS: dev-oops@scientist.com
  # MAIL_FROM_NAME: "SoftServ by Scientist.com Maintenance Department Playbook"